language: python

python: 3.6
  
sudo: true

addons:
  - firefox: latest

install:
  - pip3 install -r requirements/dev.txt
  
script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir ~/travis
  - tar xzf geckodriver-v0.24.0-linux64.tar.gz
  - cp geckodriver ~/travis
  - cd ~/travis
  - chmod +x geckodriver
  - export PATH=$PATH:~/travis/
  - cd ~
  - nosetests --with-cov --cov-config .coveragerc
  
after_success:
  - codecov
  
jobs:
  include:
    - stage: Deploy
      script: skip
    deploy:
      provider: heroku
      api_key:
      secure: Zs4PGqaV2Kog4UiEsEvzh3R1fuVRzHAhHH8QgjK+gDCcC9zZTrKzKiPgCBhp899lOWHXJOmiDuFO+rmfQZ7kKnIw/e/E3/3ro+KcgFtoZ78tdQV+TL1ecEHVvJxJ0U46PaRDp3pew31MVDci8/5Mw9NuleoqdUUutkSu80+XmrYB6EYUhwYxeZtnQdlbbhWoiOABu/5NRIsIJY/E09CsWHG/Nuw0EN+rBp7FKspeGEu6rYoSfOESzc1N1fIk2QMDSNlpGdURZyiqPQ9fu/BMXu95zdDengy5qYENEeboczibGiBVi+sYAMhNuFShsEA/EGHp87d23m57Kf63YDS9/qCHUuKUizutuazMlqAR9ajOF+nCrEEBImV77g/DmKaCql6mMKVEOIgnd7vfW8/wMunCanPrHImyMGsjjlWXzoOTWuNnEBSHInkozbQ+vm/ZHgS8WY3If/pDgfEpB0xLLysdmkvzFFrBxKJ7IzYR+AZCrpLHJt3d0U7jeBf9+sIWN4sSVVr2YyM8f7SB8ZXlHE8WEcUm9T93xYhdp2OmSSdX5n/m/xVh+Vi9LBI0IM+Z5vuN5qhsyICZtc9GQLye+j/Kvhtk8h0aNPmIGWNPbs88sJQr68KvDBmi8aoQi07ffSA5CvOP82UPLJt5KYo3SupR1UaJmP1nvWiAbB2LOo4=
      app: open-source-coffeeshop
      on:
        repo: kleii/ci_workshop
