language: python

python: 3.6
  
sudo: true

addons:
  - firefox: latest

install:
  - pip3 install -r requirements/dev.txt
  
script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir ~/travis
  - tar xzf geckodriver-v0.24.0-linux64.tar.gz
  - cp geckodriver ~/travis
  - cd ~/travis
  - chmod +x geckodriver
  - export PATH=$PATH:~/travis/
  - cd ~
  - nosetests --with-cov --cov-config .coveragerc
  
after_success:
  - codecov
  
jobs:
  include:
    - stage: Deploy
      script: skip
    deploy:
      provider: heroku
      api_key:
        secure: Cgfcdt2xzNCuywVM92pXDqzody88kehw4jAbO+PEqznX4/q2X+Idj3iQt2FD8tUJiCnC8zQ4Ms6/xBuM4XPRR/V6Uj3KUCLAZutYIdiljLpF/o5Nq1l+tE9Z9bvSLReMvQ87OiPOz4066PwxyTR9jYvSrJ2CFWJFDTBg12iPfyHKWvV6+HINmjTbRdRWuCNCxZl9bR6nSgeTxJVpb0G/rxUhqhFdtmiV6lP6d7niGcwYdLpTVS47/n8QAcjVQkA/hVDn41QpgsdFO+nMeLn7yMrL/yD+87kPoSLQHFvpBqXblepjTLQ0eMW4xDBRpyEcCrHEoTuux+CMcGtOljb3y0Ow2q1+WIVV1mD2M5VYHLwzDiC68c3DKDu1sBMaz7SLdHrY/ntI8gBa99rrfhiXFRnTgMZyaQRoFUTGaiaxe68aQbIK1pBtUguDMJHtBV2pO0EMfEDYeUX6bTHgqsPtgjRddR9NRv67MGWnc1zv7mINhwAUuwrryVFVzkBRfyyio/kMFNHC/NdT97JiAYRJz36LCnkQMoDSZhPGJZ8vt91ZEVNNHMRGLMQ+mPX9PA2FgpjIQ4WqLbQLmn7Fm7k/fhNmfHuEY8il+65/zckR9gnzHXGggBs2HqlIK+1bOgptDLFb8LITwoHBI1jwMh3rDe9uUYrmpMi9NWJuJZf6whA=
      app: open-source-coffeeshop
      on:
        repo: kleii/ci_workshop
