language: python

python: 3.6
  
sudo: true

addons:
  - firefox: latest

install:
  - pip3 install -r requirements/dev.txt
  
script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir ~/travis
  - tar xzf geckodriver-v0.24.0-linux64.tar.gz ~/travis
  - cd ~/travis
  - chmod +x geckodriver
  - export PATH=$PATH:~/travis/
  - sudo ln -s ~/travis/geckodriver geckodriver

  - nosetests --with-coverage

deploy:
  provider: heroku
  api_key:
    secure: XpzxcW1+Uk6NnrCnxbcJ76it2uixkyvuvW7Kd9TImVuUaXLpf7yEyjYeR3ZBf/t8CB/EC6JEIasnHhv9K8igSJovAbqAgkJmU/tO8+8l7IEaRF26QBe0947Sa8G6alUKPFUvIBqhAZmBvGLUvlTOkl9Cc75meXesw6y1YyH4+Sy8aHI85HC0yJ9zz53kmvwSffTJEvT1NfNakU0hbLwtnL0KTBLbOev/1yH63LPk58bzuHSvlzpRUxluUt/S1O77GFlg6dsnvDecsRQnbGeE2B/m+373aFureS5MHomNPi4z0J7BDMn5fXVxWu5mOEBGt8c2GiuPSPG5XPugO9xVyGXm1xRd+bmnm51BlAMbgBW7fBxPuSMnkerhyrOy9kOB3BsOcAFQkVJKIODy+OVWup27Mc+1QZ0z/aohBKfSEF2HplkKHIAH6yGw8Q70nd9J9CC1qSC6wpYp06fxsAsHuMbCFUDVLKmC6IB6MSK39khGmHeYu2ltL6tt2mf/bGxxqe3nXrNL1MwQz7bzC3p+r5AMjtVEoWFIpIawFm2FVNwySStVLMkptwekd2FeUCMeUYO9dbxIBdGke3NlNxo+RDvid3R7Prz7NyLedRfX9HCg3IkogqesXMtwOoP4h4znQndUrNeVBH5uQ8ho/VsBODsrz94PQjS/etpVHf8WL1o=
  on:
    branch: staging
